-- Seed dos 11 insights em src/data/insights.ts
-- Rode UMA vez no phpMyAdmin, no banco camargogallo26.

-- 1) Coluna slug. Rode o script INTEIRO uma unica vez:
--    se rodar de novo, o ALTER falha com "Duplicate column name".
ALTER TABLE insights
  ADD COLUMN slug varchar(191) DEFAULT NULL AFTER titulo,
  ADD UNIQUE KEY uq_insights_slug (slug);

-- 2) Usuario autor dos registros
SET @uid = (SELECT id FROM users WHERE username = 'admin_cg' LIMIT 1);

-- 3) Os 11 insights
INSERT INTO insights (titulo, slug, resumo, conteudo, data, categoria, imagem, user_id) VALUES
  ('A Importância da Norma NR-35 na Manutenção de Fachadas', 'importancia-da-norma-nr35', 'Entenda como a conformidade com a NR-35 garante a segurança dos trabalhadores e a tranquilidade do condomínio.', 'A NR-35 é a norma regulamentadora que estabelece os requisitos mínimos e as medidas de proteção para o trabalho em altura... [conteúdo completo simulado]', '2026-09-15', 'Normas', 'https://placehold.co/600x400?text=Norma+NR-35', @uid),
  ('As Patologias Mais Comuns em Fachadas Prediais', 'patologias-comuns-em-fachadas', 'Identifique sinais de alerta como fissuras, descolamentos e infiltrações antes que se tornem problemas graves.', 'A identificação precoce de patologias é a chave para a economia em reformas. Fissuras e desplacamentos costumam indicar problemas estruturais ou de materiais... [conteúdo completo simulado]', '2026-09-10', 'Técnica', 'https://placehold.co/600x400?text=Patologias+Fachadas', @uid),
  ('Recuperação Estrutural vs. Pintura Estética', 'recuperacao-estrutural-vs-estetica', 'Por que pintar a fachada sem tratar a estrutura é um erro comum e perigoso em condomínios.', 'Muitos síndicos optam pela pintura apenas para "renovar" o prédio, mas sem a recuperação estrutural, a pintura nova poderá descascar em pouco tempo... [conteúdo completo simulado]', '2026-09-05', 'Técnica', 'https://placehold.co/600x400?text=Recuperacao+Estrutural', @uid),
  ('Guia de Impermeabilização de Lajes de Cobertura', 'impermeabilizacao-de-lajes', 'Soluções modernas para evitar infiltrações e garantir a estanqueidade total da cobertura do edifício.', 'A impermeabilização correta é a única barreira contra as infiltrações que comprometem a laje e as unidades do último andar... [conteúdo completo simulado]', '2026-08-28', 'Prevenção', 'https://placehold.co/600x400?text=Impermeabilizacao', @uid),
  ('Retrofit de Fachadas: Modernização e Valorização do Patrimônio', 'retrofit-de-fachadas-modernizacao', 'Como a modernização da fachada pode aumentar significativamente o valor de mercado de um edifício antigo.', 'O retrofit vai além da estética; ele envolve a atualização de materiais e sistemas para melhorar a eficiência térmica e visual... [conteúdo completo simulado]', '2026-08-20', 'Cases', 'https://placehold.co/600x400?text=Retrofit+Fachadas', @uid),
  ('O Plano de Manutenção Preventiva Periódica', 'manutencao-preventiva-periodica', 'Como evitar reformas emergenciais caras através de um cronograma rigoroso de inspeções e reparos.', 'A manutenção preventiva é a melhor forma de gerir o orçamento de um condomínio, evitando surpresas desagradáveis... [conteúdo completo simulado]', '2026-08-12', 'Prevenção', 'https://placehold.co/600x400?text=Manutencao+Preventiva', @uid),
  ('Case: Recuperação de Fachada em Edifício de 20 Andares em SP', 'estudo-de-caso-recuperacao-sp', 'Análise técnica de um projeto complexo de recuperação estrutural com foco em segurança e agilidade.', 'Neste projeto, enfrentamos desafios de acesso e intempéries, utilizando técnicas avançadas de ancoragem e projeção de concreto... [conteúdo completo simulado]', '2026-08-05', 'Cases', 'https://placehold.co/600x400?text=Case+Recuperacao+SP', @uid),
  ('Problemas de Estanqueidade em Janelas e Esquadrias', 'estanqueidade-de-janelas', 'Soluções para eliminar infiltrações nas janelas sem a necessidade de trocar todo o sistema de esquadrias.', 'Muitas vezes, a infiltração não está na parede, mas na vedação entre a esquadria e a alvenaria... [conteúdo completo simulado]', '2026-07-28', 'Técnica', 'https://placehold.co/600x400?text=Estanqueidade+Janelas', @uid),
  ('A Diferença entre Pinturas Comuns e Pinturas Premium', 'pintura-premium-durabilidade', 'Por que investir em tintas de alta performance reduz a frequência de reformas a longo prazo.', 'Tintas premium possuem maior resistência a raios UV e poluição, mantendo a cor e a proteção por muito mais tempo... [conteúdo completo simulado]', '2026-07-20', 'Técnica', 'https://placehold.co/600x400?text=Pintura+Premium', @uid),
  ('Laudo de Inspeção Predial: O Primeiro Passo para a Segurança', 'importancia-da-inspecao-predial', 'Entenda por que o laudo técnico é indispensável antes de qualquer intervenção em fachadas.', 'A inspeção predial é como um check-up médico do edifício. Sem ela, qualquer obra corre o risco de ignorar a causa raiz do problema... [conteúdo completo simulado]', '2026-07-12', 'Normas', 'https://placehold.co/600x400?text=Inspecao+Predial', @uid),
  ('Como Combater o Descolamento de Pastilhas e Cerâmicas', 'combate-ao-descolamento-ceramico', 'Técnicas de teste de percussão e a importância da correta argamassa de colagem.', 'O descolamento cerâmico é um risco grave para pedestres. O teste de percussão identifica áreas ocas que precisam de intervenção imediata... [conteúdo completo simulado]', '2026-07-05', 'Técnica', 'https://placehold.co/600x400?text=Descolamento+Ceramico', @uid);
